const esbuild = require('esbuild');

async function build() {
  const shared = {
    bundle: true,
    format: 'iife',
    minify: false,
    platform: 'browser',
    target: ['chrome109', 'firefox109'],
    logLevel: 'info'
  };

  await Promise.all([
    esbuild.build({
      ...shared,
      entryPoints: ['src/content-entry.js'],
      outfile: 'content.bundle.js',
      banner: {
        js: '/* Generated by esbuild. Do not edit directly. */'
      }
    }),
    esbuild.build({
      ...shared,
      entryPoints: ['src/popup-entry.js'],
      outfile: 'browserAction/popup.bundle.js',
      banner: {
        js: '/* Generated by esbuild. Do not edit directly. */'
      }
    })
  ]);
}

build().catch((error) => {
  console.error(error);
  process.exit(1);
});
